apiVersion: v1
kind: Service
metadata:
  name: calendar-pg
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.servicePort }}