apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  selector:
    app: scheduler
  ports:
    - protocol: TCP
      port: {{ .Values.scheduler.servicePort }}
      targetPort: {{ .Values.scheduler.servicePort }}