apiVersion: v1
kind: Service
metadata:
  name: sender-service
spec:
  selector:
    app: sender
  ports:
    - protocol: TCP
      port: {{ .Values.sender.servicePort }}
      targetPort: {{ .Values.sender.servicePort }}