version: '3'

volumes:
  postgres:
    driver: local
  redis:
    driver: local

services:
  # Calendar application
  calendar_app:
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_HOST=calendar_pg
      - PG_PORT=5432
    ports:
      - '8080:8080'
    depends_on:
      - calendar_pg
      
  # Calendar database
  calendar_pg:
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data