version: '3'

volumes:
  postgres:
    driver: local
  redis:
    driver: local

services:
  # Calendar application
  calendar_app:
    build:
      context: .
      dockerfile: build/calendar/Dockerfile
    ports:
      - ${HTTP_PORT}:8080
      - ${GRPC_PORT}:50051
    depends_on:
      - calendar_pg
      - migrate

  # Scheduler application
  scheduler_app:
    build:
      context: .
      dockerfile: build/scheduler/Dockerfile
    ports:
      - ${RABBITMQ_PANEL_PORT}:15672
    depends_on:
      - calendar_pg
      - migrate
      - rabbitmq

  # Sender application
  sender_app:
    build:
      context: .
      dockerfile: build/sender/Dockerfile
    depends_on:
      - calendar_pg
      - migrate
      - rabbitmq

  # Calendar database
  calendar_pg:
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - ${PG_PORT_LOCAL}:${PG_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RABBITMQ_PORT}:5672 # AMQP port for client connections
      # - ${RABBITMQ_PANEL_PORT}:15672 # Management web interface port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  # Migration service
  migrate:
    image: golang:1.17-alpine
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["make", "local-migration-up"]
    depends_on:
      - calendar_pg
    restart: "no"