version: '3'

services:
  # Calendar application
  calendar_app:
    build:
      context: .
      dockerfile: build/calendar/Dockerfile
    ports:
      - ${HTTP_PORT}:8080
      - ${GRPC_PORT}:50051
    depends_on:
      - calendar_pg
    networks:
      - calendar_network

  # Scheduler application
  scheduler_app:
    build:
      context: .
      dockerfile: build/scheduler/Dockerfile
    depends_on:
      - calendar_pg
      - rabbitmq
    networks:
      - calendar_network

  # Sender application
  sender_app:
    build:
      context: .
      dockerfile: build/sender/Dockerfile
    depends_on:
      - calendar_pg
      - rabbitmq
    networks:
      - calendar_network

  # Calendar database
  calendar_pg:
    image: postgres:14-alpine3.17
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - ${PG_PORT_LOCAL}:${PG_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - calendar_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672 # AMQP port for client connections
      - 15672:15672 # Management web interface port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - calendar_network

volumes:
  postgres:
    driver: local
  redis:
    driver: local
    
networks:
  calendar_network:
    driver: bridge