version: '3'

services:
  # Calendar database
  calendar_pg_test:
    image: postgres:14-alpine3.17
    container_name: calendar_pg_test
    ports:
      - ${PG_PORT_LOCAL}:${PG_PORT}
    volumes:
      - postgres_test:/var/lib/postgresql/data

volumes:
  postgres_test:
    driver: local