apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: calendar_d–∞b
            - name: POSTGRES_USER
              value: calendar_user
            - name: POSTGRES_PASSWORD
              value: calendar_password
          ports:
            - containerPort: 5432